// <auto-generated />
namespace ITI.CEI.INTAKE39.MAM.LinkedIn.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateValidationToUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateValidationToUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201902201515440_updateValidationToUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
