// <auto-generated />
namespace ITI.CEI.INTAKE39.MAM.LinkedIn.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddValidationToExperienceforce : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddValidationToExperienceforce));
        
        string IMigrationMetadata.Id
        {
            get { return "201902201200171_AddValidationToExperience-force"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
